redpitaya_hostname: rp-f073ce.local
modules:
- scope
- asg0
scope:
  ch1_active: true
  ch2_active: true
  input1: in1
  input2: out1
  threshold: 0.0
  hysteresis: 0.0
  duration: 0.016777216
  trigger_delay: 0.0
  trigger_source: ch1_positive_edge
  trigger_mode: auto
  average: false
  decimation: 128
  curve_name: scope curve
  running_state: running_continuous
asg0:
  waveform: sin
  frequency: 1000.00761449337
  amplitude: 0.5
  offset: 0.0
  output_direct: out1
  trigger_source: immediately
pyrpl:
  gui: true
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: scope_config
  background_color: ''
  dock_positions: "\0\0\0\xFF\0\0\0\0\xFD\0\0\0\x01\0\0\0\x02\0\0\x03 \0\0\x02/\xFC\
    \x01\0\0\0\x01\xFC\0\0\0\0\0\0\x03 \0\0\0]\0\xFF\xFF\xFF\xFA\0\0\0\x03\x01\0\0\
    \0\v\xFB\0\0\0&\0a\0s\0g\0s\0 \0(\0s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\
    \0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0$\0i\0q\0s\0 \0(\0s\0c\0\
    o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\
    \xFB\0\0\0&\0p\0i\0d\0s\0 \0(\0s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\
    \xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0*\0s\0c\0o\0p\0e\0s\0 \0(\0\
    s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\
    \xFF\xFF\xFB\0\0\0&\0i\0i\0r\0s\0 \0(\0s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\
    \0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0(\0t\0r\0i\0g\0s\0 \0\
    (\0s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\
    \xFF\xFF\xFF\xFB\0\0\0<\0n\0e\0t\0w\0o\0r\0k\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0s\0\
    c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\
    \xFF\xFB\0\0\0>\0s\0p\0e\0c\0t\0r\0u\0m\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0s\0c\0\
    o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\
    \xFB\0\0\04\0c\0u\0r\0v\0e\0v\0i\0e\0w\0e\0r\0 \0(\0s\0c\0o\0p\0e\0_\0c\0o\0n\0\
    f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\04\0p\0y\0\
    r\0p\0l\0c\0o\0n\0f\0i\0g\0 \0(\0s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\
    \0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0,\0l\0o\0c\0k\0b\0o\0x\0 \0\
    (\0s\0c\0o\0p\0e\0_\0c\0o\0n\0f\0i\0g\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\
    \xFF\xFF\xFF\0\0\x01\xEA\0\0\0\0\0\0\0\x04\0\0\0\x04\0\0\0\b\0\0\0\b\xFC\0\0\0\
    \0"
  window_position:
  - 0
  - 0
  - 800
  - 600
redpitaya:
  autostart: true
  delay: 0.05
  frequency_correction: 1.0
  hostname: rp-f073ce.local
  leds_off: true
  monitor_server_name: monitor_server
  password: root
  port: 2222
  reloadfpga: true
  reloadserver: false
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
networkanalyzer:
  curve_name: networkanalyzer curve
spectrumanalyzer:
  curve_name: spectrumanalyzer curve
lockbox:
  sequence:
  - outputs: {}
